# -*- coding: utf-8 -*-
"""lab 3 12.09.22

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L1AFDiX2Kc6_VE-N0Awn2pYiiPEaF-nc
"""

#1
nummonth = int(input())
month = (1,2,3,4,5,6,7,8,9,10,11,12)
if nummonth in month:
  if nummonth == 1:
    print ("январь")
  elif nummonth == 2:
    print ("февраль")
  elif nummonth == 3:
    print ("март")
  elif nummonth == 4:
    print ("апрель")
  elif nummonth == 5:
    print ("май")
  elif nummonth == 6:
    print ("июнь")
  elif nummonth == 7:
    print ("июль")
  elif nummonth == 8:
    print ("август")
  elif nummonth == 9:
    print ("сентябрь")
  elif nummonth == 10:
    print ("октябрь")
  elif nummonth == 11:
    print ("ноябрь")
  else:
    print ("декабрь")
else:
  print ("Введено число без соответствующего месяца")

#2

a = int(input())
if a % 2 == 0:
  print (a," число четное") 
else:
  print (a," - число нечетное")

#3

a = int(input())
if a > 40:
  print ("stonks")
else:
  print ("not stonks")

#4

b = int(input())
def is_year_leap (b):
  if b % 4 == 0:
    return True
  else:
    return False
print (is_year_leap (b))

#5
n = int(input())
def is_prime (n):
  if n % 2 == 0 and n != 2 and n != 0:
    return False
  elif n % 3 == 0 and n != 3:
    return False
  elif n % 5 == 0 and n != 5:
    return False
  elif n % 7 == 0 and n != 7:
    return False
  else:
    return True
print (is_prime (n))

#6

a = int(input())
b = int(input())
print (a,b)
if a / b > 3.6 or (b > abs((-138/2)**1.3 ) and b < (abs(((-69/28**5.1)*4) + 1))):
  a,b = b,a
print (a,b)

#7
a = int(input())
b = int(input())
c = int(input())
d = int(input())
f = int(input())
t = 0
p = 0
j = 0
numbers = (a,b,c,d,f)
print (set(numbers), " - уникальные числа")
for i in numbers:
  if i % 2 == 0:
    t += 1
  if i < 0:
    p += 1
  if i > -256 - 1 and i < 1024 + 1:
    j += 1
print(t, " - количество четных чисел\n", p, " - количество отрицательных чисел\n", j, " - количество чисел в промежутке [-256 ; 1024].")

#1s
a = int(input())
b = int(input())
c = int(input())
o = ((a ** 2 + b ** 3) / c + 3) / 4
if o % 2 == 0:
  print (o," - четное")
else:
  print (o," - нечетное")