# -*- coding: utf-8 -*-
"""lab1_08.09.22.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LEQav4nMyepIZYgq6XXgjGE11mVID661
"""

#1
a = 5
b = int(input())
print (a * b)

#2
a = int(input())
b = int(input())
print ((a+b)**2)

#3
a = 15
b = 10
c = int(input())
print ((a + b) / c)

#4
a = int(input())
b = int(input())
c = a ** 2 + 2 * a * b + b ** 2
print (c)

#5
a = int(input())
b = int(input())
c = int(input())
s = 0.5 * a * c
p = a + b + c
print(s,p)

#6
a = int(input())
b = int(input())
c = ((a**3 + 14) / 5) * b
print (c)

#7
a = int(input())
n = int(input())
c = a ** 2 // n
print (c)

#8/1
a = float(input())
b = float(input())
c = a // b
print(int(c))

#8/2
a = int(input())
b = int(input())
s = a * b
p = a % b
print(s,p)

#1s
n = int(input())
a = n // (24*60*60)
b = n // (60*60)
c = n // 60 
print (a,b,c)

#2s
n = input()
a = n + n * 2 + n * 3
print(a)